# Generated by Django 3.0.4 on 2020-04-01 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 4, 1, 9, 34, 33, 178372, tzinfo=utc), verbose_name='date published')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.Location')),
            ],
        ),
    ]
