# Generated by Django 3.0.4 on 2020-04-01 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='star',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 10, 42, 51, 350768, tzinfo=utc), verbose_name='date published'),
        ),
    ]
