# Generated by Django 3.0.5 on 2020-04-01 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20200401_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 16, 59, 55, 491150, tzinfo=utc), verbose_name='date published'),
        ),
    ]
